- name: "Get watchman stat"
  stat:
    path: "/usr/local/bin/watchman"
  register: watchman

- name: "Install dependencies"
  apt:
    name: "autoconf"
  with_items:
    - "autoconf"
    - "libtool"
    - "pkg-config"

- name: "Unzip watchman"
  unarchive:
    src: "https://github.com/facebook/watchman/archive/v{{watchman_version}}.zip"
    remote_src: yes
    dest: "/tmp"
    creates: "/tmp/watchman-{{watchman_version}}"
  when: not watchman.stat.exists

- name: "Autogen"
  shell: "./autogen.sh"
  args:
    chdir: "/tmp/watchman-{{watchman_version}}"
  when: not watchman.stat.exists

- name: "Configure"
  shell: "./configure"
  args:
    chdir: "/tmp/watchman-{{watchman_version}}"
  when: not watchman.stat.exists

- name: "Make"
  shell: "make"
  args:
    chdir: "/tmp/watchman-{{watchman_version}}"
  when: not watchman.stat.exists

- name: "Make Install"
  shell: "make install"
  args:
    chdir: "/tmp/watchman-{{watchman_version}}"
  when: not watchman.stat.exists

- name: "Cleanup watchman"
  file:
    path: "{{item}}"
    state: "absent"
  with_items:
    - "/tmp/master-{{watchman_version}}.zip"
    - "/tmp/watchman-{{watchman_version}}"
